<?php

namespace AppBundle\Repository;

/**
 * ChickenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChickenRepository extends \Doctrine\ORM\EntityRepository
{
}
